///////////////////////////////////////////////////////////
//  IMedical.as
//  Macromedia ActionScript Implementation of the Interface IMedical
//  Generated by Enterprise Architect
//  Created on:      06-五月-2011 16:35:57
//  Original author: Anlei
///////////////////////////////////////////////////////////

package anlei.buffmodel.iface
{
	import anlei.buffmodel.utils.RoleProperty;

	/**
	 * 防具,补给,武器等接口。
	 * @author Anlei
	 * @version 1.0
	 * @created 06-五月-2011 16:35:57
	 */
	public interface IMedical
	{
		/**持续伤害时长*/
		function set totalScend(value:Number):void;
		function get totalScend():Number;
		
		/**第一次伤害值*/
		function set harFirst(value:Number):void;
		function get harFirst():Number;
		
		/**每次伤害值*/
		function set harLast(value:Number):void;
		function get harLast():Number;
		
		/**职业ID*/
		function set professionID(value:String):void;
		function get professionID():String;
		
		/**安装者*/
		function set installer(value:RoleProperty):void;
		function get installer():RoleProperty;
		
		/**是否是主动技能*/		
		function set isActive(value:Boolean):void;
		function get isActive():Boolean;
		
		/** true = 持续产生伤害, false = 播动画并只伤害一次*/
		function set momentTrigger(value:Boolean):void;
		function get momentTrigger():Boolean;
		
		/**是否可以攻击自己*/
		function set isAttackThis(value:Boolean):void;
		function get isAttackThis():Boolean;
		
		/**该装备或魔法带攻击时触发的魔法技能概率(0-100)*/
		function set trigger(value:int):void;
		function get trigger():int;
		
		/**该装备或魔法带攻击时触发的魔法技能*/
		function set iMedical(value:Vector.<IMedical>):void;
		function get iMedical():Vector.<IMedical>;
		
		/**true是装备，false是临时状态*/
		function set isES(value:Boolean):void;
		function get isES():Boolean;
		
		/**名称*/
		function set name(value:String):void;
		function get name():String;
		
		/**ID*/
		function set id(value:String):void;
		function get id():String;
		
		/**等级*/
		function set level(value:int):void;
		function get level():int;
		
		/**具有物理反弹效果，效果写在installProperty*/
		function set rebound(value:Boolean):void
		function get rebound():Boolean;
		
		/**具有吸收效果，0无， 1正向吸(攻击者具有吸收)，2反向吸（被击者具有吸收格挡）*/
		function set absorption(value:int):void;
		function get absorption():int;
		
		/**具有反弹效果，效果写在installProperty*/
		function set mRebound(value:Boolean):void
		function get mRebound():Boolean;
		
		/**负面影响，如：会受到伤害为 true(减益) 否则 false(增益)*/
		function set negative(value:Boolean):void;
		function get negative():Boolean;
		
		/**临时状态的当前执行的时间数(豪秒)。*/
		function set currTime(value:int): void;
		function get currTime(): int;
		
		/**临时状态的当前执行的累加时间数(豪秒)。*/
		function set addTime(value:int): void;
		function get addTime(): int;
		
		/**临时状态每次的执行的总时间数(豪秒)， 若为-1则是永久性*/
		function set totalTime(value:int):void;
		function get totalTime(): int;
		
		/**间隔时间(豪秒)（隔多久执行一次）*/
		function set gapTime(value:int):void;
		function get gapTime():int;
		
		/**重用时，重置初始变量*/
		function reset():void;
		
		/**反弹处理，$Attacker攻击者，$H做为反弹攻击的值*/
		function execRebound($Attacker:RoleProperty, $H:int = 0):void;
		
		/**吸收效果处理，$IRole攻击者，$H做为吸收攻击的值*/
		function execAbsorption($IRole:RoleProperty, $H:int = 0):void;
		
		/**
		 * 安置属性。$H做为反弹攻击的值。
		 * @param $IRole	被安装者
		 * @return			返回伤害值
		 */
		function installProperty($IRole:RoleProperty): int;

		/**卸载属性。*/
		function unInstallProperty($IRole:RoleProperty): void;
		
		/**释放内存资源。 */
		function dispose(): void;

	}

}